### ISSUE TITLE
Histogram and Timer converted into Summary

### ISSUE THREAD

**Issue by mikefonted** [AppMetrics/Prometheus#11]
I have started using more complex metrics and queries with histograms and timers. The fact is that I have realized that [both are converted into summary](https://github.com/alhardy/AppMetrics.Extensions.Prometheus/blob/dev/src/App.Metrics.Formatters.Prometheus/PrometheusMetricsExtensions.cs). This makes [impossible to use aggregations](https://prometheus.io/docs/practices/histograms/#quantiles) and data like lastUserValue, lastValue, max, min... seems to be lost. I have found [this other issue](https://github.com/alhardy/AppMetrics.Reporters/issues/6) where the implementation of this repository was being discussed, but it is only said that it can not be done otherwise. Is that a final decision?

**Comment by Rurouni** [comment]
Hi @mikefonted,
Yes, AppMetrics pre-aggregates histograms into percentile buckets, so summary was the only option. That makes impossible to get true probability based buckets  when aggregating over multiple nodes, but in practice avg(percentile) still gives you good enough insight into how underlying system is performing in general for uniform nodes of the same service type. 

LastUserValue is a string, I doubt you can export it into prometheus.
Max/Min/LastValue on other hand could be added as standalone Gauge time-series in theory but I didn't do it originially because I found that I always prefer percentiles than min/max in a production dashboard.
If you need them you can add it in https://github.com/alhardy/AppMetrics.Extensions.Prometheus/blob/dev/src/App.Metrics.Formatters.Prometheus/PrometheusMetricsExtensions.cs#L249
