### ISSUE TITLE
Prometheus reporting returns windows line endings which are not supported by Prometheus scrappers

### ISSUE THREAD

**Issue by astef** [AppMetrics/Prometheus#20]
I've exposed Prometheus endpoint using AppMetrics Prometheus reporting, hosted on Windows.

But Prometheus server (which is on Linux) prompts that my text endpoints contains this '\r' symbols.

Error text (from `/targets`): 

> unknown metric type "SUMMARY\r"

There's also error for proto endpoint but it is not clear for me if is the same issue:

> text format parsing error in line 1: expected float as value, got ""

**Comment by FinnNk** [comment]
I've seen the same thing. The first one is to do with the use of the string builder "writeline" method which is using an environment specific line ending. If I can find time I'll do a PR for this unless someone else fixes it first.

I don't think the proto endpoint errors are related as I still see them when my app is hosted on linux. I also see 'invalid metric name' errors from the proto endpoint - although the text endpoint works fine on linux. I haven't had a chance to look into why this is the case yet.

**Comment by FinnNk** [comment]
I had a little time to look at the cause of the second issue today - Prometheus is looking at the content type of the response to decide which format the endpoint is returning. Currently this library presents text/plain for both the text endpoint and the proto endpoint. If you change the content type returned to vnd.google.protobuf then Prometheus seems to be correctly picking up the metrics.

[Prometheus exposition formats](https://prometheus.io/docs/instrumenting/exposition_formats/#format-variants-comparison)

I'm a bit snowed under right now but if no-one else fixes this I'll open a new issue with a PR.

**Comment by Rurouni** [comment]
@FinnNk I have just run sample website in this repo and it returns `Content-Type: application/vnd.google.protobuf; proto=io.prometheus.client.MetricFamily; encoding=delimited  ` when hitting `/metrics` endpoint, so it should be something else

**Comment by FinnNk** [comment]
I wonder if it might be because we're using the 2.0.0 alpha nuget? I'm not at the computer where I was doing this right now but looking at the "dev" branch it seems fine, but if you look in the 2.0.0 branch:

https://github.com/AppMetrics/Prometheus/blob/2.0.0-refactoring/src/App.Metrics.Formatters.Prometheus/MetricsPrometheusProtobufOutputFormatter.cs

You can see where the media type is being set to text/plain.

**Comment by Rurouni** [comment]
@FinnNk  Is there specific reason why you need 2.0 alpha? If it's for netcore2/aspcore2 then you can still use stable v1. At least that's what we use in our company and it's quite stable. We are running both Prometheus and services on linux in kubernetes though.

**Comment by alhardy** [comment]
@FinnNk little testing has been done on the v2 prometheus side of things so far, as @Rurouni mentioned if you need a stable working version got with the latest v1, otherwise help in stabilizing v2 is greatly appreciated.

I've been overseas for the past couple of weeks, so haven't had the opportunity to investigate this issue. It looks like @Valyansky has kindly submitted a [PR](https://github.com/AppMetrics/Prometheus/pull/21) which fixes your first issue. I should be able to investigate sometime next week if someone else doesn't beat me to it.

**Comment by alhardy** [comment]
Found time to fix this, tested with prometheus 1.8.1 and 2.0.0-rc.2
