### ISSUE TITLE
Unit of measurement configuration

### ISSUE THREAD

**Issue by HigorCesar** [AppMetrics/Prometheus#3]
Prometheus best practices define that is a good idea to use a[ base unit of measurement](https://prometheus.io/docs/practices/naming/). So is possible to change time unit to seconds globally? Or are you planning to add this capability?

**Comment by Rurouni** [comment]
Are you talking about mapping histogram part of timer metric? 
Because Gauge/Counter/Meter report either last value or monotonically increasing count.

**Comment by HigorCesar** [comment]
Exactly @Rurouni, timer _should_ be in seconds.

**Comment by alhardy** [comment]
@HigorCesar It's not currently possible to change a timer's time unit to seconds globally atm. You can set the time unit yourself on `TimerOptions` however you won't be able to do that on the metrics recorded by `App.Metrics.Extensions.Middleware`.  

I can look at providing a global setting, but first I'd like to understand why Prometheus promotes the use of seconds for things like HTTP request durations as opposed to milliseconds, @Rurouni?

**Comment by Rurouni** [comment]
@alhardy I suppose it's because they don't support unit of measure as part of metric definition and have enough math in query language so they want to help people to not make mistakes mixing different unit of measure in queries.
I think it's probably a good idea to remap to seconds for timers in exporter by default,  but it's quite low priority because in the end App.Metrics allows you to define whatever unit of measures you want so if you want seconds just have a project specific wrapper class or extension method that defines what your default timer settings are

**Comment by alhardy** [comment]
I was thinking the same actually re mapping to seconds in the Prometheus formatter

**Comment by HigorCesar** [comment]
@alhardy I forked the repo and changed the method ToPrometheusMetrics of PrometheusMetricsExtensions. Since I want to see Prometheus metrics in the right format even in text output.

**Comment by HigorCesar** [comment]
@alhardy I forked the repo and changed the method ToPrometheusMetrics of PrometheusMetricsExtensions. Since I want to see Prometheus metrics in the right format even in text output.
https://github.com/HigorCesar/AppMetrics.Extensions.Prometheus/commit/e2d10a4cb705f28b0adcc1998330ce7a4c722e3c
Do you think this solution is good enough?

**Comment by alhardy** [comment]
@HigorCesar you would need to check the time unit before converting rather than assuming it is always milliseconds.

**Comment by HigorCesar** [comment]
@alhardy tks for your help. I updated my solution, you can see it here:
https://github.com/HigorCesar/AppMetrics.Extensions.Prometheus/commit/12ce6f87481dd3419ac2b56b344ff7258013d434
Let me know if you have a better solution, maybe I'm able to implement it as I will probably use this extension.

**Comment by alhardy** [comment]
@HigorCesar That'll work, since Prometheus recommends all durations in secs that's probably the way to go i.e. converting the unit here. I'm OK with that approach, but run it past @Rurouni this repo is pretty much his baby. I'm really just trying to keep things inline here with App.Metrics as I don't use Prometheus for any of my projects.

**Comment by HigorCesar** [comment]
@Rurouni what do you think about the proposed solution? I can write tests and create a proper pull request. what do you think?

**Comment by Rurouni** [comment]
@HigorCesar @alhardy I will add pull request today. It's even easier than we think because there already exists `TimerValue.Scale(TimeUnit)` method

**Comment by HigorCesar** [comment]
Awesome, look forward to this release

**Comment by Rurouni** [comment]
Added PR (https://github.com/alhardy/AppMetrics.Extensions.Prometheus/pull/4) with this and also apdex score will be reported as gauge now.
Not sure how health checks fit into prometheus reporter, let's leave them for now.
@alhardy If you are happy with this PR maybe worth releasing stable nuget package?

**Comment by alhardy** [comment]
@Rurouni yeah happy with that, I'll release a stable version sometime this week. Health check status values are reported as gauges so you'd already have it covered.
